#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port
    type: string
  - name: features
    type: string
    default: ""

jobs:
  - job: "ios_${{ parameters.job_name }}"
    pool:
      vmImage: macOS-11
    timeoutInMinutes: "300"
    steps:
      - powershell: brew install autoconf automake libtool

      - task: run-vcpkg@0
        displayName: "arm64-ios-simulator: ${{ parameters.port }}"
        inputs:
          vcpkgGitCommitId: "cbc22a396c88d098247fe7f79f0913a952e1f77d" # mainstream 2021-11-17
          vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
        env:
          VCPKG_DEFAULT_TRIPLET: arm64-ios-simulator
          VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports
          VCPKG_OVERLAY_TRIPLETS: $(Build.SourcesDirectory)/triplets
        condition: succeeded()

      - task: run-vcpkg@0
        displayName: "x64-ios-simulator: ${{ parameters.port }}"
        inputs:
          vcpkgGitCommitId: "cbc22a396c88d098247fe7f79f0913a952e1f77d" # mainstream 2021-11-17
          vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
        env:
          VCPKG_DEFAULT_TRIPLET: x64-ios-simulator
          VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports
          VCPKG_OVERLAY_TRIPLETS: $(Build.SourcesDirectory)/triplets
        condition: succeeded()

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.BinariesDirectory)/vcpkg/buildtrees/${{ parameters.port }}"
          Contents: |
            ?(*.log|*.txt)
            *.cmake
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
          OverWrite: true
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Staged Logs"
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "$(Agent.JobName)"
        condition: always()

    condition: or(eq(variables['Build.SourceBranchName'], 'main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/port/${{ parameters.port }}')) # https://stackoverflow.com/a/64657966
