#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port_name
    type: string

jobs:
  - job: "windows_${{ parameters.job_name }}"
    pool:
      vmImage: windows-2019
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: env
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}-test"
          target_triplet: "x64-windows"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}-test"
          target_triplet: "x86-windows"
      - powershell: pip list
        displayName: "Show installed Python packages"

  - job: "linux_${{ parameters.job_name }}"
    pool:
      vmImage: ubuntu-20.04
    dependsOn: "windows_${{ parameters.job_name }}" # Less the build stress
    steps:
      - powershell: |
          python3 -m pip install typing-extensions numpy
          pip show numpy
        displayName: "Install Python packages"
      - powershell: |
          $site_package_dir=$(python3 -m site --user-site)
          Write-Output $site_package_dir
          if (Test-Path $site_package_dir) {
            Get-ChildItem $site_package_dir
          }
        displayName: "Check Python User Site"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}-test"
          target_triplet: "x64-linux"
      - powershell: pip list
        displayName: "Show installed Python packages"

  - job: "osx_${{ parameters.job_name }}"
    pool:
      vmImage: macOS-10.15
    dependsOn: "windows_${{ parameters.job_name }}" # Less the build stress
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: pip install pybind11
        displayName: "Install Python packages"
      - powershell: env
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}-test"
          target_triplet: "x64-osx"
      - template: run-vcpkg-with-overlay.yml
        parameters:
          port_name: "${{ parameters.port_name }}-test"
          target_triplet: "arm64-osx"
      - powershell: pip list
        displayName: "Show installed Python packages"
