#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: features
    type: string
    default: ""
  - name: port
    type: string

jobs:
  - job: "windows_${{ parameters.job_name }}"
    pool:
      vmImage: windows-2019
      # vmImage: windows-2022 # (2021-10-04) VS 2022 Preview is not ready for arm64-windows
    timeoutInMinutes: "300"
    steps:
      - task: UsePythonVersion@0
        displayName: "Setup: Python 3.9"
        inputs:
          versionSpec: "3.9"
          addToPath: true
          architecture: "x64"
      - powershell: pip install typing-extensions pybind11 numpy pyyaml
        displayName: "Install Python packages"

      - task: run-vcpkg@0
        displayName: "x64-windows: ${{ parameters.port }}"
        inputs:
          vcpkgGitCommitId: "cbc22a396c88d098247fe7f79f0913a952e1f77d" # mainstream 2021-11-17
          vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports

      # - task: run-vcpkg@0
      #   displayName: "x86-windows: ${{ parameters.port }}"
      #   inputs:
      #     vcpkgGitCommitId: "a875d756749fd441305b458523df671e8f2e6cae"
      #     vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
      #   env:
      #     VCPKG_DEFAULT_TRIPLET: x86-windows
      #     VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports
      #   condition: succeeded()

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.BinariesDirectory)/vcpkg/buildtrees/${{ parameters.port }}"
          Contents: |
            ?(*.log|*.txt)
            *.cmake
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
          OverWrite: true
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Staged Logs"
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "$(Agent.JobName)"
        condition: always()

    condition: or(eq(variables['Build.SourceBranchName'], 'main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/port/${{ parameters.port }}')) # https://stackoverflow.com/a/64657966
