#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-reuse
#

parameters:
  - name: job_name
    type: string
  - name: port
    type: string
  - name: features
    type: string
    default: ""

jobs:
  - job: "android_${{ parameters.job_name }}"
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: "300"
    steps:
      - task: run-vcpkg@0
        displayName: "arm64-android: ${{ parameters.port }}"
        inputs:
          vcpkgGitCommitId: "5ddd7f02689b7c5aab78711d77f61db5d2e5e79c" # mainstream 2021-12-01
          vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
        env:
          VCPKG_DEFAULT_TRIPLET: arm64-android
          VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports
          VCPKG_OVERLAY_TRIPLETS: $(Build.SourcesDirectory)/triplets
        condition: succeeded()

      - task: run-vcpkg@0
        displayName: "arm-android: ${{ parameters.port }}"
        inputs:
          vcpkgGitCommitId: "5ddd7f02689b7c5aab78711d77f61db5d2e5e79c" # mainstream 2021-12-01
          vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
        env:
          VCPKG_DEFAULT_TRIPLET: arm-android
          VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports
          VCPKG_OVERLAY_TRIPLETS: $(Build.SourcesDirectory)/triplets
        condition: succeeded()

      - task: run-vcpkg@0
        displayName: "x64-android: ${{ parameters.port }}"
        inputs:
          vcpkgGitCommitId: "5ddd7f02689b7c5aab78711d77f61db5d2e5e79c" # mainstream 2021-12-01
          vcpkgArguments: "${{ parameters.port }}${{ parameters.features }}"
        env:
          VCPKG_DEFAULT_TRIPLET: x64-android
          VCPKG_OVERLAY_PORTS: $(Build.SourcesDirectory)/ports
          VCPKG_OVERLAY_TRIPLETS: $(Build.SourcesDirectory)/triplets
        condition: succeeded()

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Build.BinariesDirectory)/vcpkg/buildtrees/${{ parameters.port }}"
          Contents: |
            ?(*.log|*.txt)
            *.cmake
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
          OverWrite: true
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: "Publish Staged Logs"
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "$(Agent.JobName)"
        condition: always()

    condition: or(eq(variables['Build.SourceBranchName'], 'main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/port/${{ parameters.port }}')) # https://stackoverflow.com/a/64657966
