
site_name: "한글로 쓴 Vcpkg 설명서"
site_description: "Learn Vcpkg package manager with 한글(Korean)"
site_author: luncliff@gmail.com
site_url: https://luncliff.github.io/vcpkg-registry

repo_name: luncliff/vcpkg-registry
repo_url: https://github.com/luncliff/vcpkg-registry

copyright: "CC0 1.0 Public Domain"


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: 
        - en
        - ko

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luncliff
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/luncliff
    - icon: fontawesome/solid/paper-plane
      link: mailto:luncliff@gmail.com

theme:
  name: "material"
  language: "ko"
  extra:
    search:
      language: "ko"
  font:
    text: "Nanum Gothic"
    code: "Nanum Gothic Coding"
  icon:
    repo: fontawesome/brands/github
    admonition:
      tip: fontawesome/solid/gears
  palette:
    - scheme: slate
      primary: "Indigo"
      accent: "blue"
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.path
    - toc.integrate
  icon:
    logo: material/book

docs_dir: docs
nav:
  - Home: vcpkg-for-kor.md
