# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  windows_ports:
    jobs:
      - windows_2022_x64:
          filters:
            branches:
              ignore:
                - gh-pages
                - docs
                - port/swiftc
      - windows_2022_uwp:
          filters:
            branches:
              ignore:
                - gh-pages
                - docs
                - port/swiftc
          requires:
            - windows_2022_x64
      # - deploy:
      #     requires:
      #       - windows_2022_x64
      #       - windows_2022_uwp
      #     filters:
      #       branches:
      #         only: main
  linux_ports:
    jobs:
      - ubuntu_2204:
          filters:
            branches:
              ignore:
                - gh-pages
                - docs

jobs:
  windows_2022_x64:
    executor:
      name: win/server-2022 # from the Orbs
      size: large
    environment:
      VCPKG_DOWNLOADS: C:/vcpkg-downs
      VCPKG_DEFAULT_BINARY_CACHE: C:/vcpkg-bins
      # VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - checkout
      - run:
          name: "Install Chocolatey packages"
          command: |
            choco install --yes --no-progress `
              rsync ninja jq nuget.commandline
      - run:
          name: "Print with jq"
          command: |
            Get-Content .circleci/port-windows.txt | jq -Rn '[inputs]'
            Get-Content .circleci/port-uwp.txt | jq -Rn '[inputs]'
      - run:
          name: "Setup: microsoft/vcpkg(2023.06.20)"
          command: |
            New-Item -Type Directory -Force -Path $env:VCPKG_DOWNLOADS
            New-Item -Type Directory -Force -Path $env:VCPKG_DEFAULT_BINARY_CACHE
            git clone --branch=2023.06.20 --depth=1 https://github.com/microsoft/vcpkg
            Push-Location vcpkg
              ./bootstrap-vcpkg.bat
              ./vcpkg.exe --version
              ./vcpkg.exe fetch nuget
            Pop-Location
      - restore_cache:
          keys:
            - 2325-downs-{{ checksum ".circleci/config.yml" }}
      - restore_cache:
          keys:
            - 2325-bins-{{ checksum ".circleci/config.yml" }}
      - run:
          name: "Port: vcpkg-cmake"
          command: |
            ./vcpkg.exe install --debug `
              vcpkg-cmake vcpkg-cmake-config vcpkg-cmake-get-vars
          working_directory: vcpkg
      - run:
          name: "Port: from port-windows.text"
          command: |
            ./vcpkg.exe install --clean-buildtrees-after-build --overlay-ports="$env:CIRCLE_WORKING_DIRECTORY/ports" `
              $(Get-Content "$env:CIRCLE_WORKING_DIRECTORY/.circleci/port-windows.txt")
          working_directory: vcpkg
          no_output_timeout: 1h
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
           - save_cache:
              key: 2325-bins-{{ .Branch }}
              paths:
                - C:/vcpkg-bins
      - save_cache:
          key: 2325-downs-{{ checksum ".circleci/config.yml" }}
          paths:
            - C:/vcpkg-downs
          when: always
      - save_cache:
          key: 2325-bins-{{ checksum ".circleci/config.yml" }}
          paths:
            - C:/vcpkg-bins
          when: always
      # - run:
      #     name: "Stage buildtrees logs"
      #     command: rsync -r vcpkg/buildtrees/ buildtrees-log
      #     when: always
      - store_artifacts:
          name: "Upload buildtrees log"
          path: vcpkg/buildtrees/ # buildtrees-log
          destination: "build-logs"

  windows_2022_uwp:
    executor:
      name: win/server-2022
      size: large
    environment:
      VCPKG_DOWNLOADS: C:/vcpkg-downs
      VCPKG_DEFAULT_BINARY_CACHE: C:/vcpkg-bins
      # VCPKG_DEFAULT_TRIPLET: x64-uwp
    steps:
      - checkout

  ubuntu_2204:
    docker:
      - image: cimg/base:2023.07-22.04
    resource_class: large
    environment:
      VCPKG_DEFAULT_TRIPLET: x64-linux
    steps:
      - checkout
      - run:
          name: "Install APT packages"
          command: |
            sudo apt update --yes
            sudo apt install --yes zip pkg-config clang-15 clang-tools-15 llvm-15-dev libclang-15-dev
      - run:
          name: "Setup: microsoft/vcpkg(2023.06.20)"
          command: |
            git clone --branch=2023.06.20 --depth=1 https://github.com/microsoft/vcpkg
            pushd vcpkg
              ./bootstrap-vcpkg.sh
              ./vcpkg --version
            popd
      - run:
          name: "Port: llvm-staging"
          command: |
            ./vcpkg install --clean-buildtrees-after-build --clean-packages-after-build \
              llvm-staging[clang,clang-tools-extra,compiler-rt,libcxx,utils]
          working_directory: vcpkg
          no_output_timeout: 4h
          environment:
            VCPKG_OVERLAY_PORTS: /home/circleci/project/ports
            VCPKG_MAX_CONCURRENCY: 2
