name: "Windows(CUDA)"

on: [push, workflow_dispatch]

env:
  VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests,versions"

jobs:
  cuda_x64_windows:
    runs-on: ["self-hosted", "Windows", "CUDA"]
    continue-on-error: true
    timeout-minutes: 180
    env:
      VCPKG_DOWNLOADS: "C:/vcpkg/downloads"
      VCPKG_DEFAULT_BINARY_CACHE: "C:/vcpkg/archives"
      VCPKG_OVERLAY_PORTS: "${{ github.workspace }}/ports"
      VCPKG_OVERLAY_TRIPLETS: "${{ github.workspace }}/triplets"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: "create cache folders"
        run: |
          New-Item -Type Directory -Force ${env:VCPKG_DOWNLOADS}
          New-Item -Type Directory -Force ${env:VCPKG_DEFAULT_BINARY_CACHE}
          Move-Item -Path "test/self-hosted-cuda.json" -Destination "test/vcpkg.json" -Force

      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "fba75d09065fcc76a25dcf386b1d00d33f5175af" # 2024.02.14
          vcpkgJsonGlob: "test/vcpkg.json"
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--clean-buildtrees-after-build`, `--clean-packages-after-build`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
        env:
          VCPKG_DEFAULT_TRIPLET: "x64-windows"

      - uses: yumis-coconudge/clean-workspace-action@v1.0.5
        with:
          additional-path: "C:/vcpkg/installed"
