name: "Windows(CUDA)"

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests,versions"
  VCPKG_DOWNLOADS: "C:/vcpkg/downloads"
  VCPKG_DEFAULT_BINARY_CACHE: "C:/vcpkg/archives"

jobs:
  cuda_x64_windows:
    runs-on: ["self-hosted", "Windows", "CUDA"]
    continue-on-error: true
    timeout-minutes: 300
    env:
      VCPKG_OVERLAY_PORTS: "${{ github.workspace }}/ports"
      VCPKG_OVERLAY_TRIPLETS: "${{ github.workspace }}/triplets"
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: "Setup Environment"
        run: |
          New-Item -Type Directory -Force ${env:VCPKG_DOWNLOADS}
          New-Item -Type Directory -Force ${env:VCPKG_DEFAULT_BINARY_CACHE}
          Move-Item -Path "test/self-hosted-cuda.json" -Destination "test/vcpkg.json" -Force
          git config --system core.longpaths true
        shell: pwsh

      - uses: actions/cache@v4.0.2
        with:
          key: "v2419-x64-windows-cuda"
          path: |
            C:/vcpkg/downloads
            C:/vcpkg/archives

      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "943c5ef1c8f6b5e6ced092b242c8299caae2ff01" # 2024.04.26
          vcpkgJsonGlob: "test/vcpkg.json"
          runVcpkgInstall: true
          runVcpkgFormatString: '[`install`, `--keep-going`, `--clean-buildtrees-after-build`, `--clean-packages-after-build`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
        env:
          VCPKG_DEFAULT_TRIPLET: "x64-windows"

      - uses: yumis-coconudge/clean-workspace-action@v1.0.6
        with:
          additional-path: "C:/vcpkg/installed"
