name: "Request Port Update"

on:
  workflow_dispatch:
    inputs:
      release_url:
        description: 'URL to the project release'
        required: true
      pattern:
        type: choice
        description: 'Pattern of the release URL'
        options: 
          - github.com
          - gitlab.com
        required: true

permissions:
  contents: write
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "Parse GitHub URL"
        id: parse0
        if: ${{ github.event.inputs.pattern == 'github.com' }}
        run: |
          release_url="${{ github.event.inputs.release_url }}"
          org_name=$(echo $release_url | awk -F '/' '{print $4}')
          repo_name=$(echo $release_url | awk -F '/' '{print $5}')
          release_name=$(echo $release_url | awk -F '/' '{print $8}')
          echo "::set-output name=org_name::$org_name"
          echo "::set-output name=repo_name::$repo_name"
          echo "::set-output name=release_name::$release_name"

      - name: "Parse GitLab URL"
        id: parse1
        if: ${{ github.event.inputs.pattern == 'gitlab.com' }}
        run: |
          release_url="${{ github.event.inputs.release_url }}"
          org_name=$(echo $release_url | awk -F '/' '{print $4}')
          repo_name=$(echo $release_url | awk -F '/' '{print $5}')
          release_name=$(echo $release_url | awk -F '/' '{print $8}')
          echo "::set-output name=org_name::$org_name"
          echo "::set-output name=repo_name::$repo_name"
          echo "::set-output name=release_name::$release_name"

      - name: "Generate Issue Title"
        id: make_title
        run: |
          org_name="${{ steps.parse0.outputs.org_name || steps.parse1.outputs.org_name }}"
          repo_name="${{ steps.parse0.outputs.repo_name || steps.parse1.outputs.repo_name }}"
          release_name="${{ steps.parse0.outputs.release_name || steps.parse1.outputs.release_name }}"
          issue_title="Port Update - $org_name/$repo_name $release_name"
          echo "::set-output name=issue_title::$issue_title"

      - uses: dacbd/create-issue-action@v2.0.0
        with:
          token: ${{ github.token }}
          title: ${{ steps.make_title.outputs.issue_title }}
          body: |
            ## References
            * ${{ github.event.inputs.release_url }}
