name: Weekly Maintenance

on:
  schedule:
    - cron: "0 4 * * 0" # every sunday 04:00 UTC
  workflow_dispatch:

jobs:
  close-stale:
    name: "Close Stale Items"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 30
          stale-issue-label: "stale"
          days-before-pr-stale: 30
          days-before-pr-close: 30
