name: Weekly Maintenance

on:
  schedule:
    - cron: "0 22 * * 5" # Every friday 10 PM
  workflow_dispatch:

jobs:
  close-stale:
    name: "Close Stale Items"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          days-before-issue-stale: 21
          days-before-issue-close: 7
          stale-issue-label: "stale"
          days-before-pr-stale: 21
          days-before-pr-close: 7
